export const DOCTOR_SEARCHABLE_FIELDS = ["name", "email", "phone", "hospital"];

export enum SPECIALIZATION {
  CARDIOLOGY = "CARDIOLOGY",
  DERMATOLOGY = "DERMATOLOGY",
  NEUROLOGY = "NEUROLOGY",
  PEDIATRICS = "PEDIATRICS",
  GYNECOLOGY = "GYNECOLOGY",
  ORTHOPEDICS = "ORTHOPEDICS",
  ENT = "ENT",
  OPHTHALMOLOGY = "OPHTHALMOLOGY",
  GENERAL_MEDICINE = "GENERAL_MEDICINE",
  GENERAL_SURGERY = "GENERAL_SURGERY",
  PSYCHIATRY = "PSYCHIATRY",
  DENTISTRY = "DENTISTRY",
  OTHER = "OTHER",
}
